# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 776)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.windowSizeTxt = QtWidgets.QLineEdit(self.tab)
        self.windowSizeTxt.setObjectName("windowSizeTxt")
        self.gridLayout.addWidget(self.windowSizeTxt, 2, 1, 1, 1)
        self.currentSystemTxt = QtWidgets.QLineEdit(self.tab)
        self.currentSystemTxt.setObjectName("currentSystemTxt")
        self.gridLayout.addWidget(self.currentSystemTxt, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.maxDistanceTxt = QtWidgets.QLineEdit(self.tab)
        self.maxDistanceTxt.setObjectName("maxDistanceTxt")
        self.gridLayout.addWidget(self.maxDistanceTxt, 3, 1, 1, 1)
        self.minProfitTxt = QtWidgets.QLineEdit(self.tab)
        self.minProfitTxt.setObjectName("minProfitTxt")
        self.gridLayout.addWidget(self.minProfitTxt, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.searchBtn = QtWidgets.QPushButton(self.tab)
        self.searchBtn.setObjectName("searchBtn")
        self.verticalLayout.addWidget(self.searchBtn)
        self.SearchResultTable = QtWidgets.QTableView(self.tab)
        self.SearchResultTable.setObjectName("SearchResultTable")
        self.verticalLayout.addWidget(self.SearchResultTable)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.editMenu = QtWidgets.QMenu(self.menubar)
        self.editMenu.setObjectName("editMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.optionsMenu = QtWidgets.QAction(MainWindow)
        self.optionsMenu.setObjectName("optionsMenu")
        self.editMenu.addAction(self.optionsMenu)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.editMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.currentSystemTxt)
        MainWindow.setTabOrder(self.currentSystemTxt, self.windowSizeTxt)
        MainWindow.setTabOrder(self.windowSizeTxt, self.maxDistanceTxt)
        MainWindow.setTabOrder(self.maxDistanceTxt, self.minProfitTxt)
        MainWindow.setTabOrder(self.minProfitTxt, self.searchBtn)
        MainWindow.setTabOrder(self.searchBtn, self.SearchResultTable)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Window size"))
        self.label_4.setText(_translate("MainWindow", "Min profit"))
        self.label.setText(_translate("MainWindow", "Current system"))
        self.label_3.setText(_translate("MainWindow", "Max distance"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.editMenu.setTitle(_translate("MainWindow", "Edit"))
        self.optionsMenu.setText(_translate("MainWindow", "Options"))

