# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\ui\Options.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(551, 445)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.EDDBUpdateIntervalTxt = QtWidgets.QSpinBox(Dialog)
        self.EDDBUpdateIntervalTxt.setObjectName("EDDBUpdateIntervalTxt")
        self.horizontalLayout_2.addWidget(self.EDDBUpdateIntervalTxt)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.udpateEDDBBtn = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.udpateEDDBBtn.sizePolicy().hasHeightForWidth())
        self.udpateEDDBBtn.setSizePolicy(sizePolicy)
        self.udpateEDDBBtn.setObjectName("udpateEDDBBtn")
        self.horizontalLayout_2.addWidget(self.udpateEDDBBtn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.EDCEPathTxt = QtWidgets.QLineEdit(Dialog)
        self.EDCEPathTxt.setObjectName("EDCEPathTxt")
        self.horizontalLayout_4.addWidget(self.EDCEPathTxt)
        self.EDCEPathBtn = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EDCEPathBtn.sizePolicy().hasHeightForWidth())
        self.EDCEPathBtn.setSizePolicy(sizePolicy)
        self.EDCEPathBtn.setObjectName("EDCEPathBtn")
        self.horizontalLayout_4.addWidget(self.EDCEPathBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.soundStartupTxt = QtWidgets.QLineEdit(Dialog)
        self.soundStartupTxt.setObjectName("soundStartupTxt")
        self.horizontalLayout_6.addWidget(self.soundStartupTxt)
        self.soundStartupBtn = QtWidgets.QPushButton(Dialog)
        self.soundStartupBtn.setObjectName("soundStartupBtn")
        self.horizontalLayout_6.addWidget(self.soundStartupBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 11, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.soundErrorTxt = QtWidgets.QLineEdit(Dialog)
        self.soundErrorTxt.setObjectName("soundErrorTxt")
        self.horizontalLayout_9.addWidget(self.soundErrorTxt)
        self.soundErrorBtn = QtWidgets.QPushButton(Dialog)
        self.soundErrorBtn.setObjectName("soundErrorBtn")
        self.horizontalLayout_9.addWidget(self.soundErrorBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 13, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 13, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.soundSearchTxt = QtWidgets.QLineEdit(Dialog)
        self.soundSearchTxt.setObjectName("soundSearchTxt")
        self.horizontalLayout_8.addWidget(self.soundSearchTxt)
        self.soundSearchBtn = QtWidgets.QPushButton(Dialog)
        self.soundSearchBtn.setObjectName("soundSearchBtn")
        self.horizontalLayout_8.addWidget(self.soundSearchBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 12, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 15, 1, 1, 1)
        self.MarketValidVal = QtWidgets.QSpinBox(Dialog)
        self.MarketValidVal.setObjectName("MarketValidVal")
        self.gridLayout_2.addWidget(self.MarketValidVal, 4, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.soundVolumeSlider = QtWidgets.QSlider(Dialog)
        self.soundVolumeSlider.setMaximum(100)
        self.soundVolumeSlider.setProperty("value", 100)
        self.soundVolumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.soundVolumeSlider.setObjectName("soundVolumeSlider")
        self.horizontalLayout_7.addWidget(self.soundVolumeSlider)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 10, 1, 1, 1)
        self.soundEnabledChk = QtWidgets.QCheckBox(Dialog)
        self.soundEnabledChk.setObjectName("soundEnabledChk")
        self.gridLayout_2.addWidget(self.soundEnabledChk, 10, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 12, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 11, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.testEdceBtn = QtWidgets.QPushButton(Dialog)
        self.testEdceBtn.setObjectName("testEdceBtn")
        self.horizontalLayout_5.addWidget(self.testEdceBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 9, 1, 1, 1)
        self.edceConnectionStatusTxt = QtWidgets.QLabel(Dialog)
        self.edceConnectionStatusTxt.setText("")
        self.edceConnectionStatusTxt.setObjectName("edceConnectionStatusTxt")
        self.gridLayout_2.addWidget(self.edceConnectionStatusTxt, 14, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.passwordTxt = QtWidgets.QLineEdit(Dialog)
        self.passwordTxt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordTxt.setObjectName("passwordTxt")
        self.gridLayout_2.addWidget(self.passwordTxt, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.usernameTxt = QtWidgets.QLineEdit(Dialog)
        self.usernameTxt.setObjectName("usernameTxt")
        self.gridLayout_2.addWidget(self.usernameTxt, 5, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(Dialog)
        self.label_51.setObjectName("label_51")
        self.gridLayout_2.addWidget(self.label_51, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem1)
        self.closeBtn = QtWidgets.QPushButton(Dialog)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_51.addWidget(self.closeBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_51, 16, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ElitePathTxt = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ElitePathTxt.sizePolicy().hasHeightForWidth())
        self.ElitePathTxt.setSizePolicy(sizePolicy)
        self.ElitePathTxt.setObjectName("ElitePathTxt")
        self.horizontalLayout_3.addWidget(self.ElitePathTxt)
        self.ElitePathBtn = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ElitePathBtn.sizePolicy().hasHeightForWidth())
        self.ElitePathBtn.setSizePolicy(sizePolicy)
        self.ElitePathBtn.setObjectName("ElitePathBtn")
        self.horizontalLayout_3.addWidget(self.ElitePathBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 7, 0, 1, 1)
        self.edceUploadsResultsCheck = QtWidgets.QCheckBox(Dialog)
        self.edceUploadsResultsCheck.setText("")
        self.edceUploadsResultsCheck.setObjectName("edceUploadsResultsCheck")
        self.gridLayout_2.addWidget(self.edceUploadsResultsCheck, 7, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.EDDBUpdateIntervalTxt, self.udpateEDDBBtn)
        Dialog.setTabOrder(self.udpateEDDBBtn, self.ElitePathTxt)
        Dialog.setTabOrder(self.ElitePathTxt, self.ElitePathBtn)
        Dialog.setTabOrder(self.ElitePathBtn, self.EDCEPathTxt)
        Dialog.setTabOrder(self.EDCEPathTxt, self.EDCEPathBtn)
        Dialog.setTabOrder(self.EDCEPathBtn, self.MarketValidVal)
        Dialog.setTabOrder(self.MarketValidVal, self.usernameTxt)
        Dialog.setTabOrder(self.usernameTxt, self.passwordTxt)
        Dialog.setTabOrder(self.passwordTxt, self.edceUploadsResultsCheck)
        Dialog.setTabOrder(self.edceUploadsResultsCheck, self.testEdceBtn)
        Dialog.setTabOrder(self.testEdceBtn, self.soundEnabledChk)
        Dialog.setTabOrder(self.soundEnabledChk, self.soundVolumeSlider)
        Dialog.setTabOrder(self.soundVolumeSlider, self.soundStartupTxt)
        Dialog.setTabOrder(self.soundStartupTxt, self.soundStartupBtn)
        Dialog.setTabOrder(self.soundStartupBtn, self.soundSearchTxt)
        Dialog.setTabOrder(self.soundSearchTxt, self.soundSearchBtn)
        Dialog.setTabOrder(self.soundSearchBtn, self.soundErrorTxt)
        Dialog.setTabOrder(self.soundErrorTxt, self.soundErrorBtn)
        Dialog.setTabOrder(self.soundErrorBtn, self.closeBtn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Options"))
        self.label_2.setText(_translate("Dialog", "h"))
        self.udpateEDDBBtn.setText(_translate("Dialog", "Update now"))
        self.EDCEPathBtn.setText(_translate("Dialog", "..."))
        self.soundStartupBtn.setText(_translate("Dialog", "..."))
        self.soundErrorBtn.setText(_translate("Dialog", "..."))
        self.label_10.setText(_translate("Dialog", "Error sound"))
        self.soundSearchBtn.setText(_translate("Dialog", "..."))
        self.label_9.setText(_translate("Dialog", "Volume"))
        self.soundEnabledChk.setText(_translate("Dialog", "Enable sounds"))
        self.label_8.setText(_translate("Dialog", "Automatic Search Sound"))
        self.label_7.setText(_translate("Dialog", "Startup Sound"))
        self.label_4.setText(_translate("Dialog", "EDCE path"))
        self.testEdceBtn.setText(_translate("Dialog", "Test EDCE connection"))
        self.label_5.setText(_translate("Dialog", "Market expire days"))
        self.label_6.setText(_translate("Dialog", "Elite password (for EDCE)"))
        self.label_51.setText(_translate("Dialog", "Elite username (for EDCE)"))
        self.label.setText(_translate("Dialog", "EDDB update interval"))
        self.label_3.setText(_translate("Dialog", "Elite path"))
        self.closeBtn.setText(_translate("Dialog", "Close"))
        self.ElitePathBtn.setText(_translate("Dialog", "..."))
        self.label_11.setText(_translate("Dialog", "Edce uploads results to EDDB"))

